
apiVersion: 1
datasources:
  - name: influxdb-k6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    basicAuth: false
    isDefault: true
    database: k6
    user: admin
    password: admin123
    jsonData:
      version: "1"
    secureJsonData: {}
