
apiVersion: 1
notifiers:
  - name: "Slack - LexGPT Alerts"
    type: "slack"
    isDefault: false
    uid: "slack-lexgpt"
    settings:
      url: "FILL_ME_SLACK_WEBHOOK"
      recipient: ""
  - name: "SMTP - LexGPT Alerts"
    type: "smtp"
    isDefault: false
    uid: "smtp-lexgpt"
    settings:
      host: "FILL_ME_SMTP_HOST"
      port: 587
      user: "FILL_ME_SMTP_USER"
      password: "FILL_ME_SMTP_PASSWORD"
      fromAddress: "FILL_ME_FROM_ADDRESS"
      fromName: "Grafana"
      skipTlsVerify: false
